name: Deploy Website on Push

on:
  push:
    branches: [ "main" ] # Or your main branch

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Server
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://your_server_ip_or_domain:your_webhook_port/deploy-website' # Replace with your webhook URL
          method: 'POST'
          data: '{ "ref": "${{ github.ref }}", "before": "${{ github.before }}", "after": "${{ github.after }}", "repository": { "full_name": "${{ github.repository }}" } }'
          header: 'Content-Type: application/json'
          secret: 'YOUR_GITHUB_WEBHOOK_SECRET' # Ensure this matches your webhook listener config
